# ブログのタイトル
title: "チリも積もれば旅となる"

# ブログの説明文（メタタグやテーマによってトップページ等に表示されます）
description: "関西在住のぽぽとももの夫婦が財テクを駆使して、旅を楽しむブログです"

# 使用するデザインテーマ
remote_theme: mmistakes/minimal-mistakes

# スキンの選択（カラーテーマ）
# 選択肢: "default", "air", "aqua", "contrast", "dark", "neon", "mint", "sunrise" など
minimal_mistakes_skin: "air"

# 言語設定（日付の表示などを日本語にするため）
locale: "ja-JP"

# サイドバーに表示するプロフィール設定
author:
  name   : "ぽぽ"
  bio    : "夫婦が財テクを駆使して旅を楽しむブログです。"
  # avatar : "/assets/images/biophoto.jpg" # 顔写真やアイコン画像を使う場合
  links:
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/popomomo-ux"
    - label: "カテゴリー一覧"
      icon: "fas fa-fw fa-folder-open" # フォルダのアイコン
      url: "/popomomoblog/categories/"           # 作成したカテゴリーページのURL
    - label: "タグ一覧"
      icon: "fas fa-fw fa-folder-open" # フォルダのアイコン
      url: "/popomomoblog/tags/"           # 作成したタグページのURL
    - label: "サイト内検索"
      icon: "fas fa-fw fa-search"
      url: "/popomomoblog/search/"

# 利用プラグイン
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# あなたのブログのURL（[ユーザー名]の部分をご自身のGitHubアカウント名に変更してください）
url: "https://popomomo-ux.github.io"

# サブディレクトリを使わずにルート直下で公開する場合は空欄のままでOKです
baseurl: "/popomomoblog"

# ページや記事全体のデフォルト設定
defaults:
  - scope:
      path: ""
    values:
      author_profile: true

# 検索機能の設定
search: false
search_provider: "lunr"
